#
# 로컬 환경 설정
#
spring:
  # DB 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coding-Ground?characterEncoding=UTF-8&useTimezone=true&serverTimezone=Asia/Seoul
    username: root
    password: 123456



# 파일 업로드 경로
file:
#  directory: /Users/igor/Desktop/upload/
  directory: C:/upload/
