name: Backend build and ECR

on:
  release:
    types:
    - published
      
env:
  ecr_url: 503237308475.dkr.ecr.ca-central-1.amazonaws.com
  aws_region: ca-central-1

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the version from Git tag
        id: version
        run: |
          VERSION=${{ github.event.release.tag_name }}
          if [[ $VERSION =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "::set-output name=version::$VERSION"
          else
            echo "Version information not found in the Git tag. Skipping build."
            exit 1
          fi

      - name: Build Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: |
            codingground-backend:${{ steps.version.outputs.version }}
          file: ./Dockerfile

      - name: Docker Image Check
        id: Check
        run: |
          docker images

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: ${{ env.aws_region }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
      - name: Push Image to ECR
        run: |
          docker tag codingground-backend:${{ steps.version.outputs.version }} ${{ env.ecr_url }}/codingground-backend:${{ steps.version.outputs.version }}
          docker tag ${{ env.ecr_url }}/codingground-backend:${{ steps.version.outputs.version }} ${{ env.ecr_url }}/codingground-backend:latest
          docker push ${{ env.ecr_url }}/codingground-backend:${{ steps.version.outputs.version }}
          docker push ${{ env.ecr_url }}/codingground-backend:latest

      - name: Docker Image Check 2
        id: Check 2
        run: |
          docker images